controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


profile:
    path: '/profile'
    controller: 'App\Controller\ProfileController::index'

devis_new:
    path: '/devis/new'
    controller: 'App\Controller\DevisController::new'
    methods: ['GET', 'POST']

devis_delete:
    path: '/devis/{id}/delete'
    controller: 'App\Controller\DevisController::delete'
    methods: ['POST']